"""add image for category

Revision ID: e2507dba9c85
Revises: 895bfe628f96
Create Date: 2024-07-27 17:17:15.991674

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2507dba9c85'
down_revision: Union[str, None] = '895bfe628f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image', sqlmodel.sql.sqltypes.AutoString(length=2083), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'image')
    # ### end Alembic commands ###
